using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

[Serializable]
public class AttackHitBox : MonoBehaviour
{
    private ActionHitBoxClip clip;
    public AttackConfig config;

    public void Init(ActionHitBoxClip clip)
    {
        this.config = clip.attackConfig;
        this.clip = clip;
    }

    private void OnTriggerEnter(Collider other)
    {
        // МьВщЪЧЗёдкЕаШЫВу
        if (((1 << other.gameObject.layer) & config.targetLayers) != 0)
        {
            if (other.TryGetComponent<IDamageable>(out var damageable))
            {
                // ДДНЈЙЅЛїЪ§Он
                AttackHitData hitData = new AttackHitData(
                    damage: config._baseDamage,
                    attacker: clip._hitboxObject.transform.root.gameObject,
                    hitPoint: other.ClosestPoint(clip._hitboxObject.transform.position)
                );

                // ДІРэЩЫКІ
                damageable.TakeDamage(hitData);

                if (config._debugMode)
                {
                    Debug.Log($"[ЙЅЛїУќжа] ФПБъ: {other.name}, ЩЫКІ: {config._baseDamage}");
                }
            }
        }
    }

}

public struct AttackHitData
{
    public float Damage { get; }
    public GameObject Attacker { get; }
    public Vector3 HitPoint { get; }

    public AttackHitData(float damage, GameObject attacker, Vector3 hitPoint)
    {
        Damage = damage;
        Attacker = attacker;
        HitPoint = hitPoint;
    }

}